version: '3'
services:
    rabbit1:
      image: harbur/rabbitmq-cluster
      hostname: rabbit1
      environment:
        - ERLANG_COOKIE=abcdefg
      networks:
        - balancernet  
      ports:
        - "5672:5672"
        - "15672:15672"
    rabbit2:
      image: harbur/rabbitmq-cluster
      hostname: rabbit2
      links:
        - rabbit1
      environment:
        - ERLANG_COOKIE=abcdefg
        - CLUSTER_WITH=rabbit1
        - ENABLE_RAM=true
        - RAM_NODE=true
      networks:
        - balancernet  
      ports:
        - "5673:5672"
        - "15673:15672"
    rabbit3:
      image: harbur/rabbitmq-cluster
      hostname: rabbit3
      links:
        - rabbit1
        - rabbit2
      environment:
        - ERLANG_COOKIE=abcdefg
        - CLUSTER_WITH=rabbit1
      networks:
        - balancernet
      ports:
        - "5674:5672"
        
    slackloadbalancer:    
        image: slackloadbalancer:latest
        depends_on:
          - rabbit1
          - rabbit2
          - rabbit3
        networks:
          - balancernet
        links:
          - rabbit1
          - rabbit2
          - rabbit3
networks:
  balancernet:
    driver: overlay